name: souffleur
description: A cross platform remote control for presentations
publish_to: 'none'

version: 1.1.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  barcode_scan2: ^4.2.4
  http: ^1.1.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  shake: ^2.2.0
  vibration: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
flutter_intl:
  enabled: true
